# To make a release:
# 1. Push changes to main
# 2. Create a tag and push it
# ```
# git tag -a v1.x.x -m "message"
# git push origin v1.x.x
# This action will run to package up the plugin
name: Release
on:
  push:
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'ltiadv.zip'
        exclusions: '*.git*'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "ltiadv.zip"
        token: ${{ secrets.GITHUB_TOKEN }}