name: Release
on:
  push:
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'ltiadv.zip'
        exclusions: '*.git*'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "ltiadv.zip"
        token: ${{ secrets.GITHUB_TOKEN }}